services:
  nmt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8501:8501"
    volumes:
      - ../datasets:/workspace/datasets
      - ../models:/workspace/models
      - ../experiments:/workspace/experiments
      - ../reports:/workspace/reports
